apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: noders-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: noders-mining-service